CREATE TABLE ACCOUNT (
    ACCOUNT_ID VARCHAR(7) NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    PROFILE VARCHAR(280) ,
    BIRTHDAY DATE NOT NULL,
    MAILADDRESS VARCHAR(256) NOT NULL,
    CREATEDBY TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDBY TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ACCOUNT_ID)
);

